[package]
name = "rust-cratesio-6028"
description = "Minimal Complete Verifiable Example for crates.io#6208"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

publish = ["staging"]

[dependencies]
